name: VaultWeapons
version: '${project.version}'
main: me.sunmc.vw.VaultWeapons
api-version: '1.21'
author: SunMC

commands:
  vaultweapons:
    aliases: [ vw ]
    description: Main VaultWeapons command
    usage: /vaultweapons <list|recipe|give|reload>
    permission: vaultweapons.use

permissions:
  vaultweapons.use:
    description: Allows use of /vw recipe and /vw list
    default: true
  vaultweapons.admin:
    description: Allows /vw give and /vw reload
    default: op